.gitignore
auto-content-creator/agents/package.json
auto-content-creator/agents/src/index.ts
auto-content-creator/agents/src/routes/writer.ts
auto-content-creator/agents/src/services/threadStorage.ts
auto-content-creator/agents/src/services/writerAgent.ts
auto-content-creator/agents/src/types.ts

Closes #13 
This pull request introduces significant changes to the `auto-content-creator/agents` module, focusing on adding SQLite-based persistent storage for thread states and enhancing the writer agent's functionality. The main updates include integrating SQLite for thread storage, updating the server initialization process, and adding new endpoints for thread state management.
* **`auto-content-creator/agents/package.json`**: Added `sqlite3` and `sqlite` dependencies for database operations.
* **`auto-content-creator/agents/src/services/threadStorage.ts`**: Implemented SQLite-based storage for thread states, including functions for saving, loading, and cleaning up thread data.
* **`auto-content-creator/agents/src/services/writerAgent.ts`**: Integrated the new thread storage system …

Add thread persistence to agents

---

auto-kol/agent-memory-viewer/frontend/src/components/Analytics.tsx

- I had made a typo in the GA ID
- No reason to have it as a env since it get expose on the client side anyway

Remove use of env and fix analytic id

---

auto-kol/agent/src/services/agents/nodes/autoApprovalNode.ts
auto-kol/agent/src/services/agents/nodes/engagementNode.ts
auto-kol/agent/src/services/agents/workflow.ts

There was a bug in how we were handling batch processing.
1. `parsedContent` is JSON and we have to parse it to Number to correctly handle the cursor on indexes when processing the second batch to end. 
2. autoApprovalNode must return the `currentTweetIndex` as well as `tweets` to complete the workflow.
p.s. I highly suggest to move the unnecessary variables like `currentTweetIndex` to out of scope of `messages`.  I'll fix and open a seperate PR for this.
I tested multiple times with more than 100 tweets for processing, it did well and didn't hit the recursion limit.

fix a bug in batch processing - state management and type handling

---

auto-kol/agent/src/services/agents/nodes/autoApprovalNode.ts
auto-kol/agent/src/services/agents/nodes/responseGenerationNode.ts
auto-kol/agent/src/services/agents/prompts.ts
auto-kol/agent/src/services/twitter/api.ts

This pull request includes several changes to improve logging, code readability, and functionality in the `auto-kol/agent` module. The most important changes are grouped into logging improvements and functionality enhancements.
Logging improvements:
* Added logging for tweet processing details in `createResponseGenerationNode` to provide better traceability of tweet handling.
* Added logging for response strategy details in `createResponseGenerationNode` to aid in debugging and analysis of response generation.
* Improved logging messages in `ExtendedScraper` to provide clearer information during re-authentication attempts and when fetching initial tweets. [[1]](diffhunk://#diff-a8b668c7aec0047d0cd6ae657c60d25756faf09a98297780f85ce9810c1ac06aL61-R61) …

Update prompt to end endless threads + cleanups

---

auto-agents-framework/.env.sample
auto-agents-framework/src/agents/tools/utils/agentMemoryContract.ts
auto-agents-framework/src/agents/tools/utils/agentWallet.ts
auto-agents-framework/src/config/index.ts
auto-agents-framework/src/config/schema.ts

This PR is addressing issue #94

Add zod for config format - clean coding and refactoring

---

auto-agents-framework/src/agents/workflows/kol/nodes/engagementNode.ts
auto-agents-framework/src/agents/workflows/kol/nodes/generateTweetNode.ts
auto-agents-framework/src/agents/workflows/kol/schemas.ts
auto-agents-framework/src/services/twitter/client.ts
auto-agents-framework/src/services/twitter/convertFromTimeline.ts
auto-agents-framework/tests/agents/workflows/kol/nodes/engagementNode.test.ts

This PR addresses two cases where not enough info regarding a tweet was being passed to the LLM:
- Content of quote tweets were not being included
- Excess text in long posts was being ignored
Enhancements to tweet processing:
* [`auto-agents-framework/src/agents/workflows/kol/nodes/engagementNode.ts`](diffhunk://#diff-2b6657036a29ea9e83af31f8d759fbdb53a14a8c6a792cdc252b90264ea50929R15-R24): Added handling for quoted tweets in the `getEngagementDecision` and `createEngagementNode` functions. [[1]](diffhunk://#diff-2b6657036a29ea9e83af31f8d759fbdb53a14a8c6a792cdc252b90264ea50929R15-R24) [[2]](diffhunk://#diff-2b6657036a29ea9e83af31f8d759fbdb53a14a8c6a792cdc252b90264ea50929L53-R76)
* [`auto-agents-framework/src/agents/workflows/kol/nodes/generateTweetNode.ts`](diffhunk://#diff-00ebb8f71961a6 …

Tweet Processing Enhancements

---

config/config.example.yaml
src/config/index.ts

We will want to add some better checking around config values.

fix auto_drive typo in config.example.yaml

---

README.md

The name of the default character is changed and was not reflected in doc

Fix character copy command

---

README.md
package.json
src/cli/onboarding.ts
src/cli/utils/characterLoader.ts
src/index.ts
src/utils/characterLoader.ts
yarn.lock

This PR improves the ux for selecting a character in the application.
Additionally, it addresses two minor corrections:
- Version Fix: Corrected the version field in package.json.
- Typo Correction: Updated `autodrive` to `auto_drive` in the README.

Enhance Character Selection UX and Fix Minor Typos

---

src/services/twitter/client.ts

I encounter an issue with cookies, where every time I launched the agent, it will fail twitter login till I deleted the .cookies to force it to login from scratch.
This change add a second attempt to login from scratch if using the cookies fail.

Add a second login attempt if using the cookie fail

---

agent-memory-viewer/backend/src/db/init.ts
agent-memory-viewer/backend/src/db/postgres/connection.ts
agent-memory-viewer/backend/src/db/repositories/memoryRepository.ts
agent-memory-viewer/backend/src/utils/resurrection.ts

Previously, we had to wait until the resurrection is complete, then it starts to writing the experiences into the DB. But now, we are doing it over an interval, like 10 experiences. It would enhance the UI as we can see the newest experiences immediately.
Also, I removed duplicated code and integerated connection with init file.

Enhancing the resurrection - Clean coding

---

src/agents/tools/saveExperienceTool.ts
src/agents/tools/twitterTools.ts
src/agents/tools/vectorDbTools.ts
src/agents/workflows/orchestrator/nodes/inputNode.ts
src/agents/workflows/orchestrator/orchestratorWorkflow.ts
src/agents/workflows/orchestrator/prompts.ts
src/index.ts
src/services/twitter/client.ts
src/services/vectorDb/VectorDB.ts

With these changes along with a better initial input prompt, we are able to run orchestration workflows with significant autonomy. I am leaving the[ "Run the twitter workflow"](https://github.com/autonomys/autonomys-agents/blob/37b2676e1af6928adb06858c8c25616ca690ce6f/src/index.ts#L20) input prompt for this PR as I am working on a better way to handle initial and ongoing prompts. An example prompt that will potentially lead to more autonomy would is:
```
Ongoing goal: Establish as an expert in the field of AI and blockchain technology, particularly in the areas of decentralized AI agents and Web3. You are seeking engagement with the community and an ever growing following. Additional goal, grow awareness of the Autonomy Network and the Autonomys Agent framework.
DO NOT RUN TWITTER …
```

Prompt optimizations - Improve ability to autonomously carry out workflows

---

src/agents/tools/twitterTools.ts
src/services/twitter/client.ts
src/services/twitter/types.ts

This pull request introduces new tools for interacting with the Twitter API in the `src/agents/tools/twitterTools.ts` file. The most important changes include the addition of tools for liking tweets, following users, and fetching the "following" timeline , as well as updating the `createAllTwitterTools` function to include these new tools.
New tools added:
* [`createLikeTweetTool`](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75R133-R142): This tool allows users to like a tweet by providing the tweet ID.
* [`createFollowUserTool`](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75R181-R213): This tool allows users to follow a user by providing the user ID.
Updates to existing functions:
* …

Add tools to like tweets, follow users and fetch the "following" timeline

---

src/agents/tools/twitterTools.ts
src/services/twitter/client.ts

This pull request introduces new tools for fetching Twitter user profiles and their following list, and updates existing functionality to support these new tools. The most important changes include adding new tools to the `twitterTools` module and updating the `twitterApi` service to fetch user IDs by username.
New tools added:
* [`src/agents/tools/twitterTools.ts`](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75R145-R166): Added `createFetchFollowingTool` to fetch the following list of a given Twitter user.
* [`src/agents/tools/twitterTools.ts`](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75R145-R166): Added `createFetchProfileTool` to fetch the profile of a given Twitter user.
Updates to existing functionality:
* …

Add fetchFollowing and fetchProfile tools

---

package.json
src/agents/tools/getTimeTool.ts
src/agents/workflows/orchestrator/tools.ts
src/index.ts

This pull request includes several changes to the `autonomys-agents` project, focusing on adding a new tool for getting the current time, updating dependencies, and improving workflow execution.
* [`src/agents/tools/getTimeTool.ts`](diffhunk://#diff-df931fed9abe73b6131ddcb8e9b8c898ac30818510adf289c7b6c265e8ab08c2R1-R12): Introduced a new `createGetCurrentTimeTool` function that returns the current time in ISO format using the `DynamicStructuredTool` from `@langchain/core/tools` and `zod` for schema validation.
* [`src/agents/workflows/orchestrator/tools.ts`](diffhunk://#diff-55b82f5fb1f170f81a7e10c667ea1ad850222cc4534cafb9784a12b4781e9a49L7-R29): Added the `createGetCurrentTimeTool` to the list of tools in the orchestrator workflow.
* …

Add tool for retrieving current time

---

src/agents/workflows/orchestrator/orchestratorWorkflow.ts
src/agents/workflows/orchestrator/tools.ts
src/agents/workflows/orchestrator/types.ts
src/index.ts

We want to move to being able to create custom agents that follow the orchestrator workflow and can then be exposed as tools to higher level agents. This PR is the first step in generalizing the orchestrator with custom tools and prompts. The way it is instantiated in `index.ts` is still a hack, using tools and prompts from the orchestration workflow. This will be cleaned up in a follow-up PR that will create a more autonomous twitter agent based on the generalized orchestrator workflow.

Refactor orchestrator workflow to be instantiable with tools and prompts

---

agent-memory-viewer/backend/src/utils/agentMemoryContract.ts

This pull request includes several improvements to the `AgentWatcher` class in the `agent-memory-viewer/backend/src/utils/agentMemoryContract.ts` file. The changes primarily focus on enhancing the health check mechanism and improving the reconnection logic.
* Introduced a timeout for the health check to prevent it from hanging indefinitely. The health check now races between the actual health check promise and a timeout promise, logging a success message if the health check passes.
* Enhanced the logging of health check failures to include the error message for better debugging.
* Added a cap to the retry count to prevent excessive delays while maintaining exponential backoff, with a maximum delay of 1 minute.
* Ensured the system is fully stopped and cleared any existing state before …

Fix healthcheck connection bug in memory-viewer

---

characters/character.example/config/config.example.yaml
src/agents/workflows/orchestrator/workflowTools/promptSummarizer.ts
src/config/llm.ts
src/config/schema.ts
src/services/llm/factory.ts
src/services/llm/types.ts

This pull request includes significant changes to the configuration and usage of language models (LLMs) in the project. The primary focus is on removing the `LLMSize` enum and updating the configuration to use `provider` and `model` directly. Additionally, a new `prompt_summarizer` node has been added to the configuration.
* [`characters/character.example/config/config.example.yaml`](diffhunk://#diff-6a55d5e703079797ee7a217d463353d9e7fa206bc335e8a326dd5cfe320434d6L17-R41): Removed `LLMSize` and updated nodes to use `provider` and `model` directly. Added a new `prompt_summarizer` node.
* [`src/config/llm.ts`](diffhunk://#diff-8f632f74d7dfae168c70c35406f95a9d09c6ae85f1e9069c98d6a2f5e895efefL1-R32): Updated default configuration to use `provider` and `model` instead of `size`. Added …

Refactor LLM Configuration: Replace LLMSize with provider & model

---

src/agents/workflows/orchestrator/nodes/inputNode.ts
src/agents/workflows/orchestrator/nodes/workflowSummaryPrompt.ts
src/agents/workflows/orchestrator/orchestratorWorkflow.ts
src/agents/workflows/orchestrator/types.ts
src/services/llm/factory.ts

Currently, we bind tools to the orchestrator model at the config level. However, we only want tools bound during the input node execution. This PR moves binding of tools to the orchestrator model call in the input node.
* [`src/agents/workflows/orchestrator/nodes/inputNode.ts`](diffhunk://#diff-0b266f27dd6b3b72ff592a029a20a2e6b185b4a148a142c29da1c950e6f1b3aaL21-R32): Updated the `createInputNode` function to include `toolNode` in the `OrchestratorConfig` and bind tools to the orchestrator model before invoking it.
* [`src/agents/workflows/orchestrator/orchestratorWorkflow.ts`](diffhunk://#diff-b4dfd7878eec16efd1a0380da0464e07cc47af54ed1dc55b5fc0aefef7644059L23-R23): Modified the `createWorkflowConfig` function to remove the binding of tools to the orchestrator model during its creation.
* …

Only bind tools to input node

---

README.md
characters/character.example/config/config.example.yaml
src/agent.ts
src/agents/workflows/orchestrator/nodes.ts
src/agents/workflows/orchestrator/nodes/inputNode.ts
src/agents/workflows/orchestrator/nodes/messageSummaryNode.ts
src/agents/workflows/orchestrator/nodes/workflowSummaryNode.ts
src/agents/workflows/orchestrator/orchestratorWorkflow.ts
src/agents/workflows/orchestrator/state.ts
src/agents/workflows/orchestrator/types.ts
src/agents/workflows/twitter/twitterAgentTool.ts
src/config/llm.ts
src/config/schema.ts
src/services/vectorDb/VectorDB.ts

Closes #214 and Closes #199 
This pull request introduces updates to the orchestrator configuration and context size management, refactors the code to remove unnecessary dependencies, and enhances the documentation. The most important changes include the addition of context size management, dynamic configuration for the orchestrator, and refactoring to remove the `VectorDB` dependency from several nodes.
* Added a new section on context size management in `README.md`, detailing how to configure pruning parameters both statically and dynamically.
* Updated the `README.md` to include network configuration for the Taurus EVM wallet.
* Introduced pruning parameters (`maxWindowSummary` and `maxQueueSize`) in the orchestrator configuration to manage the context window size dynamically. …

Refactor Orchestrator Configuration for Instance-Level Model Selection and Context Management

---

src/agent.ts
src/agents/workflows/orchestrator/nodes.ts
src/agents/workflows/orchestrator/nodes/finishWorkflowNode.ts
src/agents/workflows/orchestrator/nodes/finishWorkflowPrompt.ts
src/agents/workflows/orchestrator/nodes/inputPrompt.ts
src/agents/workflows/orchestrator/orchestratorWorkflow.ts
src/agents/workflows/orchestrator/prompts.ts
src/agents/workflows/orchestrator/types.ts
src/agents/workflows/twitter/prompts.ts
src/index.ts
src/services/vectorDb/VectorDB.ts

closes #189 
The goal of this PR was to introduce the first step in agent-driven scheduling of tasks. With this update, an agent has the option to `selfSchedule` which will return a next suggested prompt and how long to wait until running the workflow again. This system is an improvement over the interval driven current approach, but will need to be upgraded to be able to take other actions while waiting. This will likely be implemented with a message queue system of some sort, to be determined.
* Replaced `workflowSummaryNode` with `finishWorkflowNode` in the orchestration workflow. This includes changes in `src/agents/workflows/orchestrator/nodes.ts`, `src/agents/workflows/orchestrator/orchestratorWorkflow.ts`, and `src/agents/workflows/orchestrator/prompts.ts`. …

Feature: Agent can self-schedule workflow

---

examples/autonomousTwitterAgent/index.ts
examples/directedTwitterAgent/index.ts
src/agents/tools/getTimeTool.ts
src/agents/tools/saveExperienceTool.ts
src/agents/tools/webSearchTool.ts
src/agents/workflows/orchestrator/nodes/finishWorkflowNode.ts
src/agents/workflows/orchestrator/nodes/finishWorkflowPrompt.ts
src/agents/workflows/orchestrator/nodes/inputPrompt.ts
src/agents/workflows/orchestrator/orchestratorWorkflow.ts
src/agents/workflows/twitter/prompts.ts

This PR is an attempt to improve agent behavior via clearer prompting. Attempts were made to improve clarity while also remaining generalized, but this is not always successful. This will be an ongoing experiment. I must say, this feels more like psychology or parenting than software development. Strange times we live in... Specific areas addressed include:
- Behavior where agent thinks you are requesting workflow to be run immediately after completing a child workflow. Addressed via clear indication that the information being returned by a child workflow is based on actions taken by the that workflow. Any reference to "workflow" is removed from association with the summary.
- Sometimes agents refuse to believe the response of the `get_current_time` tool is accurate, instead insisting …

Improve agent behavior through clearer prompts

---

.github/workflows/build.yaml

This pull request introduces a new job in the GitHub Actions workflow to build the Agent Framework. The most important change includes adding a new job definition in the `.github/workflows/build.yaml` file.
New job added to the GitHub Actions workflow:
* [`.github/workflows/build.yaml`](diffhunk://#diff-d0777657fa3fd81d23aaf7273e58aee453b04e67882517900c56daeef9b3e4c1R53-R73): Added a new job named `build-agent-framework` that runs on `ubuntu-latest`, checks out the repository, sets up Node.js, enables Corepack, installs dependencies, and builds the project.

Add git build for agent framework

---

examples/twitterAgent/index.ts
src/agent.ts
src/agents/tools/twitterTools.ts
src/agents/workflows/orchestrator/tools.ts
src/agents/workflows/twitter/tools.ts
src/agents/workflows/twitter/twitterAgentTool.ts
src/services/twitter/client.ts
src/services/twitter/types.ts

Closes #95 
This pull request includes several changes to the Twitter agent tools and orchestrator configurations. The primary focus is on simplifying the tool creation process and improving the tweet posting functionality.
* [`src/agents/tools/twitterTools.ts`](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75L298-R293): Changed the return type of `createAllTwitterTools` to an array instead of an object. [[1]](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75L298-R293) [[2]](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75L310-R305)
* [`src/agents/workflows/orchestrator/tools.ts`](diffhunk://#diff-55b82f5fb1f170f81a7e10c667ea1ad850222cc4534cafb9784a12b4781e9a49L7-R7): Changed the return type …

Return Tweet ID after Posting Tweet and Tool Cleanup

---

src/agents/tools/twitter/index.ts

This pull request fixes an issue where agents would post replies to same tweet multiple times. The most changes update the `createFetchTimelineTool` and `createFetchFollowingTimelineTool` functions to exclude replied-to tweet IDs when fetching timelines.
* [`src/agents/tools/twitter/index.ts`](diffhunk://#diff-68013515fdfb5afcfacecec26f158f622461c5e4a30072c0bfcd9d1f4d4d1d6cL26-R29): Updated the `createFetchTimelineTool` function to fetch replied-to tweet IDs and include them in the processed IDs when retrieving the user's timeline.
* [`src/agents/tools/twitter/index.ts`](diffhunk://#diff-68013515fdfb5afcfacecec26f158f622461c5e4a30072c0bfcd9d1f4d4d1d6cR59-R64): Updated the `createFetchFollowingTimelineTool` function to fetch replied-to tweet IDs and include them in the processed IDs when …

Bug: Agents post replies to same tweet multiple times

---

characters/character.example/config/config.example.yaml
examples/multiPersonality/index.ts
examples/twitterAgent/index.ts
src/agent.ts
src/config/index.ts
src/config/schema.ts

Before this, the CLI default code enables monitoring. This moves it to the character config.
This pull request introduces a new feature to enable monitoring in the auto drive configuration across multiple files. The changes include updates to the configuration files, schema, and relevant TypeScript files to support this new feature.
Key changes include:
Configuration Updates:
* Added `monitoring` option to `auto_drive` configuration in `config.example.yaml`
* Updated `config/index.ts` to include `AUTO_DRIVE_MONITORING` with a default value
Schema Updates:
* Added `AUTO_DRIVE_MONITORING` to the `autoDriveConfigSchema` in `schema.ts`
Codebase Updates:
* Modified `orchestratorConfig` in `index.ts` and `agent.ts` to include `monitoringEnabled` and update the `monitoring` property accordingly …

Add monitoring option to autodrive config

---

cli/components/body/InputBox.ts

When the input box label wrapped, the text in the input box wasn't visible.
This pull request includes a small change to the `cli/components/body/InputBox.ts` file. The change adds padding to the top and enables text wrapping in the `createInputBox` function. 
* [`cli/components/body/InputBox.ts`](diffhunk://#diff-aa7e78dd93b547709d2f23bb816ffb94557e40d7a810b4dd0cead3edd0b414a0R25-R27): Added top padding and enabled text wrapping in the `createInputBox` function.

Bug: Fix CLI input label wrapping issue

---

package.json
src/agents/tools/arxiv/index.ts
yarn.lock

This pull request includes the addition of a new tool for querying the arXiv API and updates to the `package.json` dependencies to support this new functionality. The most important changes include the introduction of the `createArxivSearchTool` function and the addition of new dependencies required for XML parsing and logging.
* [`src/agents/tools/arxiv/index.ts`](diffhunk://#diff-6629c59e103855b4fb6c0bc7614a319bc4b9e68c12e49b83265cce2cd601b014R1-R235): Introduced `createArxivSearchTool`, a new tool for querying the arXiv API with advanced filters, sorting, and author filtering. This tool returns an array of papers with detailed information including title, authors, publication date, summary, arXiv link, and direct PDF download link.
* …

Add arxiv search tool

---

src/agents/workflows/orchestrator/orchestratorWorkflow.ts
src/services/vectorDb/vectorDBPool.ts

Previously, we encountered an issue where database commits were not taking effect immediately after data insertion. The solution was to close the database once the workflow was complete.

resolve vecdb commit issue

---

examples/multiPersonality/index.ts
examples/twitterAgent/index.ts
src/agent.ts
src/agents/tools/slack/chat.ts
src/agents/workflows/orchestrator/nodes/finishWorkflowPrompt.ts
src/agents/workflows/orchestrator/nodes/inputPrompt.ts
src/agents/workflows/orchestrator/orchestratorWorkflow.ts
src/agents/workflows/orchestrator/prompts.ts
src/agents/workflows/orchestrator/scheduler/taskQueue.ts
src/agents/workflows/slack/prompts.ts
src/agents/workflows/slack/slackAgent.ts
src/agents/workflows/twitter/twitterAgent.ts
src/utils/logger.ts

This pull request includes several changes to streamline the workflow configuration and execution by removing the `selfSchedule` feature and simplifying related code. This change is possible because of the recently added scheduler tools 🚀.
* [`examples/multiPersonality/index.ts`](diffhunk://#diff-382b3edb1966ece3ac02aa287f74366a97388952eff7d60fe16d48dfd6433fc2L61-R61): Removed the `selfSchedule` parameter from `createPrompts` and simplified the workflow execution result handling. [[1]](diffhunk://#diff-382b3edb1966ece3ac02aa287f74366a97388952eff7d60fe16d48dfd6433fc2L61-R61) [[2]](diffhunk://#diff-382b3edb1966ece3ac02aa287f74366a97388952eff7d60fe16d48dfd6433fc2L108-R112)
* [`examples/twitterAgent/index.ts`](diffhunk://#diff-b53615d38e5708e50f68e83b8a6dd0f9a1c3abddf56555240661d0ae643cb5a4L49 …

Remove concept of self-schedule from finish workflow node

---

src/agents/workflows/slack/prompts.ts

Simply adding in the slack agent prompts how user pin should be use

Improve slack agent prompt for user pin

---

src/api/controller/LogsController.ts
src/api/controller/TaskController.ts

This change is necessary since `keep-alive` is forbidden in HTTP/2

Remove `keep-alive` from agent api header

---

src/agents/workflows/orchestrator/orchestratorWorkflow.ts
src/agents/workflows/orchestrator/scheduler/taskExecutor.ts
src/agents/workflows/orchestrator/scheduler/taskQueue.ts
src/agents/workflows/orchestrator/scheduler/types.ts

This PR resolves #352  - "Scheduler bug: Cannot get next task, a task is already running"
When a task encounters a recursion limit error, it can get stuck in the "processing" state. This causes subsequent attempts to run new tasks to fail with:
```
Cannot get next task, a task is already running in namespace: orchestrator
```
This leaves the orchestrator in an inconsistent state requiring manual intervention to fix.
- Restructured try/catch blocks in the task executor to properly detect and handle recursion limit errors
- Added specific handling for recursion limit errors that automatically marks failed tasks appropriately
```ts
if (error instanceof Error && error.message.includes('Recursion limit') && dueTask) {
runner.updateTaskStatus(dueTask.id, 'failed', error.message);
}
```
- …

Fix for Scheduler "Task Already Running" Bug

---

README.md
scripts/start.ts
src/api/server.ts
src/config/index.ts
src/config/schema.ts

This PR adds support for running agents in headless mode, allowing operation without the API server.
- Added `--headless` flag to disable the API server when running characters
- Updated command parsing in `scripts/start.ts` to handle flags
- Added conditional API initialization based on the headless flag
- Updated configuration schema to include API enablement option
- Added documentation for headless mode usage in README
Characters can now be run without the API server using:
```
yarn dev <character-name> --headless
yarn start <character-name> --headless
```
This is useful for environments where the API interface is not needed or for deployment scenarios that only require the core agent functionality.

Add Headless Mode Support

---

core/src/blockchain/agentExperience/cidManager.ts
core/src/blockchain/agentExperience/index.ts
core/src/blockchain/agentExperience/types.ts

There was a remaining edge case of RPC failure that was not handled correctly when saving the last memory CID.
This pull request includes changes to improve error handling and type definitions in the `cidManager` and `ExperienceManager` components of the blockchain agent experience module. The most important changes include updating the `saveLastMemoryCid` function to handle errors more gracefully, modifying the `ExperienceManager` to handle potential undefined values, and updating type definitions accordingly.
Error handling improvements:
* [`core/src/blockchain/agentExperience/cidManager.ts`](diffhunk://#diff-685328590728df7385c5e596c7cb9bc5641a5797a1f392251f656a4c91263cb6L145-R164): Updated the `saveLastMemoryCid` function to handle errors more gracefully by saving the hash locally …

Bug: Update saveLastMemoryCid to handle RPC call failure gracefully

---

core/src/blockchain/agentExperience/cidManager.ts
core/src/blockchain/agentExperience/index.ts
core/src/blockchain/agentExperience/types.ts

Previously, the code handled the case of a bad RPC on initialization. However, it didn't properly handle a 404 error from a live RPC. This has been hard to test properly, but luckily (😅) we had a node failing with a 404 yesterday so gave the opportunity for more thorough testing. 
An improvement can be made to periodically try to reconnect to the failed RPC rather than going permanently into local mode, but for now this should be sufficient. #383 
- Added fallback to local-only storage when RPC provider connection fails
- Updated return types to use `undefined` instead of `null` for better type safety
- Simplified error handling in both `getLastMemoryCid` and `saveLastMemoryCid` methods
- Modified `ExperienceManager` types to match implementation

Bug: RPC could still fail during initialization

---

core/src/agents/tools/thinking/index.ts
core/src/agents/workflows/orchestrator/nodes/inputPrompt.ts
core/src/agents/workflows/orchestrator/tools.ts

OpenAI usage of tools have less internal reflection than Anthropic's usage of tools which leads to less than optimal outcomes at times. This pull request introduces a new `thinking` tool to enhance the decision-making process in the workflow. The most important changes include the creation of the `thinking` tool, its integration into the workflow, and updates to the input prompt instructions to utilize this new tool.
* [`core/src/agents/tools/thinking/index.ts`](diffhunk://#diff-466e27a0aafc028c7fffc56fd9ab62d779f472810e1c3ee783ee496feff282c5R1-R18): Added the `createThinkingTool` function, which defines the `thinking` tool to help users reflect, analyze options, and plan their next steps without taking external actions.
* [`core/src/agents/workflows/orchestrator/tools.ts`](diffhunk://#dif …

Add thinking tool

---

agent-memory-viewer/backend/package.json
agent-memory-viewer/backend/src/utils/backgroundProcessor.ts
agent-memory-viewer/backend/src/utils/dsn.ts
agent-memory-viewer/backend/src/utils/resurrection.ts
agent-memory-viewer/backend/src/utils/validation/memory.ts
agent-memory-viewer/backend/yarn.lock

This PR updates the memory-viewer to use the gateway instead of the auto-drive package. The reason for this change is that the gateway can resolve CIDs on both mainnet and testnet, whereas the auto-drive package makes this difficult since it doesn't indicate whether the received CID belongs to mainnet or testnet.

Update Memory viewer To Use Autonomys Gateway

---

README.md
agent-package-manager/CHANGELOG.md
agent-package-manager/README.md
agent-package-manager/package.json
agent-package-manager/src/commands/clean.ts
agent-package-manager/src/commands/config.ts
agent-package-manager/src/commands/init.ts
agent-package-manager/src/commands/install.ts
agent-package-manager/src/commands/publish.ts
agent-package-manager/src/config/default.ts
agent-package-manager/src/config/prompts.ts
agent-package-manager/src/index.ts
agent-package-manager/src/utils/autoDrive/autoDriveClient.ts
agent-package-manager/src/utils/commands/install/utils.ts
agent-package-manager/src/utils/commands/registry/toolPublish.ts
agent-package-manager/src/utils/credential/index.ts
agent-package-manager/src/utils/shared/path.ts
agent-package-manager/yarn.lock

This PR is following our discussion about matching package and cli command. Everything is set to `agent-os` now.
V0.1.1 will be published upon PR approval.

rename autoOS to agent-os

---

README.md
agent-package-manager/CHANGELOG.md
agent-package-manager/src/commands/init.ts
core/CHANGELOG.md
core/README.md
core/src/agents/tools/twitter/types.ts
core/src/config/config.ts
examples/multiPersonality/README.md
examples/twitterAgent/README.md
examples/web3Agent/README.md

This PR includes two main improvements:
1. Command-line argument syntax standardization:
- Updated the `--workspace` flag syntax across all documentation and code files to use space separator instead of equals sign
- Changed from `--workspace=/path/to/workspace` to `--workspace /path/to/workspace`
- This change makes the syntax more consistent with common CLI patterns
- Updated in README files, example documentation, and code output messages
2. Twitter client type improvements:
- Enhanced type exports from 'agent-twitter-client'
- Added explicit type annotations using the `type` keyword for better type safety
- Affects Tweet and Profile type imports/exports

Fix workspace flag syntax typo and improve Twitter client types

---

agent-package-manager/CHANGELOG.md
agent-package-manager/package.json
agent-package-manager/src/commands/init.ts
agent-package-manager/src/commands/install.ts
agent-package-manager/src/commands/publish.ts
agent-package-manager/src/commands/tool.ts
agent-package-manager/src/commands/update.ts
agent-package-manager/src/index.ts
agent-package-manager/src/types/index.ts
agent-package-manager/src/utils/npm/index.ts
agent-package-manager/src/utils/update/index.ts

This PR adds a new `update` command to the agent-os CLI, allowing users to check for and install updates to the package.
- Added new `update` command to check for newest version and upgrade the agent-os
- Added update checking functionality to existing commands (init, install, publish, tool)
- Created utility functions to check npm package information
- Bumped version from 0.1.2 to 0.1.3
- Updated CHANGELOG.md with new version information
- `agent-os update` - Checks for updates to the CLI
- `agent-os update --auto` - Automatically installs the latest version if available
- Added update check to existing commands to notify users when a new version is available
- The update functionality uses axios to query the npm registry
- Update checks display current version vs latest version if an …

(feature): Add Update Command to agent-os

---

characters/character.example/config/.env.example
core/src/agents/chat/config.ts
core/src/agents/chat/nodes.ts
core/src/agents/chat/nodes/input.ts
core/src/agents/chat/tools.ts
core/src/agents/chat/types.ts
core/src/agents/chat/workflow.ts
core/src/agents/workflows/github/githubAgent.ts
core/src/agents/workflows/orchestrator/config.ts
core/src/agents/workflows/orchestrator/nodes.ts
core/src/agents/workflows/orchestrator/nodes/finishWorkflowNode.ts
core/src/agents/workflows/orchestrator/nodes/inputNode.ts
core/src/agents/workflows/orchestrator/nodes/messageSummaryNode.ts
core/src/agents/workflows/orchestrator/tools.ts
core/src/agents/workflows/orchestrator/types.ts
core/src/agents/workflows/slack/slackAgent.ts
core/src/agents/workflows/twitter/twitterAgent.ts
core/src/api/types.ts
core/src/config/config.ts
core/src/config/schema.ts
core/src/services/llm/factory.ts
core/src/services/llm/types.ts
core/src/services/vectorDb/VectorDB.ts
core/src/services/vectorDb/vectorDBPool.ts
examples/twitterAgent/index.ts
package.json
yarn.lock

This PR continues the implementation of the chat workflow system started in Part 1 (PR #416), focusing on LLM configuration simplification and environment variable standardization.
Langchain has built-in functions to load the credentials if they are available as environment variables in runtime. Since we load all the credentials from the character env file, it is unnecessary to have llmConfig.
This is the **second part** of our planned PR series for the chat workflow implementation. This PR focuses on:
1. Simplifying the LLM configuration across the codebase
2. Standardizing environment variable names
3. Removing redundant configuration passing
- Removed `llmConfig` parameter from workflow configurations
- Previously, LLM API keys were passed through multiple layers unnecessarily
- Now …

Streamlining and Simplifying LLM Configuration (Part 2)

---

README.md
docker/web-cli/docker-compose.yml
docker/web-cli/entrypoint.sh

These changes are necessary following PR #419

remove `/api` extension from web-cli docker
