autonomys/autonomys-agents

auto-content-creator/frontend/src/components/ContentView.tsx
- Add copy button next to "Final Content"
- Add copy button next to draft dropbox
=> Add copy buttons

auto-content-creator/frontend/src/components/ContentGenerator.tsx
- Add checkbox to automatically redirect on completion
- Center and size green button with blue button
=> Redirect to generated content option

auto_content_creator/main.py
This pull request includes several changes to the `main` function in `auto_content_creator/main.py` to enhance the article generation process by including the article title and category. The most important changes include adding the title to the unpacked values, passing the category to the `generate_article` and `save_article` functions, and converting the title to a string to satisfy type hints.
Enhancements to article generation:
* [`auto_content_creator/main.py`](diffhunk://#diff-d2da22b7ffe9ed5e708d47c5b7499e105dfeff9fc624f6452c6db98fe1506478L17-R18): Modified the `main` function to include the article title and category in the unpacked values from `generate_article`, and passed the category to both `generate_article` and `save_article` functions. …
=> Fix python implementation

README.md
Add information about auto-chain-agent to root README.md
=> Add information about auto-chain-agent to root README.md

auto-kol/frontend/src/pages/Dashboard.tsx, auto-kol/frontend/src/pages/Responses.tsx
This pull request introduces several enhancements to the `Dashboard` and `Responses` pages in the `auto-kol` frontend. The key changes include adding navigation links to the dashboard statistics and improving the responses handling with better state management and user feedback.
* Added `RouterLink` from `react-router-dom` to enable navigation to detailed views of pending responses and skipped tweets from the dashboard. [[1]](diffhunk://#diff-7d7573ef173afa7893fe000a1d41119ac06005819232f6dacab3eecbe125e326R2) [[2]](diffhunk://#diff-7d7573ef173afa7893fe000a1d41119ac06005819232f6dacab3eecbe125e326R20-R27) [[3]](diffhunk://#diff-7d7573ef173afa7893fe000a1d41119ac06005819232f6dacab3eecbe125e326R39-R57)
* Introduced local state management for responses and processing state using `useState`.
* …
=> Minor Updates to KOL Frontend

auto-kol/README.md, auto-kol/agent/README.md, auto-kol/agent/src/services/twitter/api.ts
Revert `getThread` simplifications and update README
=> Fix mentions workflow

auto-kol/agent/.env.sample, auto-kol/agent/README.md, auto-kol/agent/src/config/index.ts, auto-kol/agent/src/services/agents/nodes.ts, auto-kol/agent/src/services/agents/prompts.ts, auto-kol/agent/src/services/twitter/api.ts, auto-kol/agent/src/utils/dsn.ts, auto-kol/agent/src/utils/twitter.ts
Add ability to skip DSN upload and encrypt uploads.
Closes #54 #53
=> Improve DSN Upload Options

auto-kol/agent/src/utils/dsn.ts
As it will soon get messy when multiple agent are running and uploading file that all are name very similarly
=> Pass in the twitter username in the agent memory file name

auto-kol/README.md
Add instruction for ChromaDB in the main auto-kol readme
=> Improve auto-kol main readme

auto-kol/agent/src/services/agents/nodes/engagementNode.ts, auto-kol/agent/src/services/agents/nodes/recheckSkippedNode.ts, auto-kol/agent/src/services/agents/workflow.ts
This PR is following the previous PR #75 
The further updates are:
* Updating the workflow
* Update the state management in rechecNode
=> fix the problem in workflow and recheck node

auto-kol/agent/src/utils/twitter.ts
Checks for missing `full_text` on timeline tweets before processing them
=> Ensure full_text exists on timeline tweets before processing

auto-kol/agent/src/utils/twitter.ts
Previously was targeting bug/batch-processing branch.
=> ensure full_text exists on timeline tweets

auto-kol/agent/src/services/agents/nodes/autoApprovalNode.ts, auto-kol/agent/src/services/agents/nodes/engagementNode.ts, auto-kol/agent/src/services/agents/nodes/responseGenerationNode.ts, auto-kol/agent/src/utils/agentMemoryContract.ts, auto-kol/agent/src/utils/dsn.ts
This pull request focusing on improving the handling of CID retrieval and memory hash operations. The most important changes are grouped by theme below:
* [`auto-kol/agent/src/services/agents/nodes/autoApprovalNode.ts`](diffhunk://#diff-5ae667d5a9f70141e2de5f436020b8b1c4c3136f62788e9279e239eb6f41d834L69): Removed the `previousCid` parameter from the `uploadToDsn` function calls. [[1]](diffhunk://#diff-5ae667d5a9f70141e2de5f436020b8b1c4c3136f62788e9279e239eb6f41d834L69) [[2]](diffhunk://#diff-5ae667d5a9f70141e2de5f436020b8b1c4c3136f62788e9279e239eb6f41d834L81)
* [`auto-kol/agent/src/services/agents/nodes/engagementNode.ts`](diffhunk://#diff-d333c0bdc8ee26c19993e1a3abd26ac85f4c9dd97bbbb960c0275cbd52ffa419L41): Removed the `previousCid` parameter from the `uploadToDsn` function call.
* …
=> Use smart contract last memory cid as fallback

auto-kol/agent/src/services/agents/prompts.ts, auto-kol/agent/src/services/twitter/api.ts, auto-kol/agent/src/tools/index.ts, auto-kol/agent/src/tools/tools/fetchTimelineTool.ts, auto-kol/agent/src/tools/tools/tweetSearchTool.ts, auto-kol/agent/src/utils/twitter.ts
This pull request includes several changes to improve code consistency, enhance functionality, and fix minor issues. The most important changes are grouped by theme below:
* Replaced double quotes with single quotes in `auto-kol/agent/src/services/agents/prompts.ts` for consistency. [[1]](diffhunk://#diff-973e0075d74884422e809cb4ad1527c8dfd346190d08a19004f61cb15a25842fL122-R155) [[2]](diffhunk://#diff-973e0075d74884422e809cb4ad1527c8dfd346190d08a19004f61cb15a25842fL175-R189) [[3]](diffhunk://#diff-973e0075d74884422e809cb4ad1527c8dfd346190d08a19004f61cb15a25842fL210-R222)
* Corrected possessive apostrophes in multiple prompts in `auto-kol/agent/src/services/agents/prompts.ts`. [[1]](diffhunk://#diff-973e0075d74884422e809cb4ad1527c8dfd346190d08a19004f61cb15a25842fL34-R40) …
=> Updates to twitter api usage and getThread optimization

auto-agents-framework/src/agents/tools/fetchTimelineTool.ts, auto-agents-framework/src/agents/tools/postTweetTool.ts, auto-agents-framework/src/agents/workflows/kol/nodes/generateTweetNode.ts, auto-agents-framework/src/agents/workflows/kol/prompts.ts, auto-agents-framework/src/services/twitter/client.ts
This pull request includes several changes to improve the functionality and reliability of the Twitter API integration in the `auto-agents-framework` project. The most important changes include slicing the timeline tweets, updating the post tweet tool to fetch the latest tweet, and refactoring the conversation fetching logic.
Improvements to fetching timeline and posting tweets:
* [`auto-agents-framework/src/agents/tools/fetchTimelineTool.ts`](diffhunk://#diff-eff5e4c2479b9e3143f6ec26ddef93eea0c8adbc99b71c8dc64476515d9cfd9bL32-R34): Modified the `createFetchTimelineTool` function to slice the timeline tweets to the specified number of tweets.
* [`auto-agents-framework/src/agents/tools/postTweetTool.ts`](diffhunk://#diff-33266d9c260e50c50ddf73ffeed2339089aee799b82ed0eec2a5f41673a63d23L20-R3 …
=> Improve Twitter client interactions

auto-agents-framework/.gitignore, auto-agents-framework/README.md, auto-agents-framework/src/agents/workflows/kol/nodes/analyzeTrendNode.ts, auto-agents-framework/src/agents/workflows/kol/nodes/engagementNode.ts, auto-agents-framework/src/agents/workflows/kol/nodes/generateTweetNode.ts, auto-agents-framework/src/agents/workflows/kol/prompts.ts, auto-agents-framework/src/agents/workflows/kol/types.ts, auto-agents-framework/src/agents/workflows/kol/workflow.ts, auto-agents-framework/src/config/index.ts, auto-agents-framework/src/index.ts
This pull request introduces several important changes to the `auto-agents-framework` project, primarily focusing on enhancing prompt management and configuration. The changes include restructuring prompts to be dynamically loaded based on character files, updating workflow configurations to support these changes, and ensuring proper directory management.
Closes #102 
* [`auto-agents-framework/src/agents/workflows/kol/prompts.ts`](diffhunk://#diff-2e9fbcc21ad4ae5bc17a1f1b46f9b2502a0f9939ecf2be0af95a7c2090e35bf0L23-R32): Refactored prompts to be dynamically loaded based on character files, and created a new `createPrompts` function to handle this process. [[1]](diffhunk://#diff-2e9fbcc21ad4ae5bc17a1f1b46f9b2502a0f9939ecf2be0af95a7c2090e35bf0L23-R32) …
=> Add cli option to select a character file

auto-agents-framework/src/services/twitter/client.ts
Addressing issue #113. Changed the logic from `push` to `unshift` and correct the direction of building tweet chain.
=> fix issue #113

README.md
This pull request includes a change to the `README.md` file to update the framework's name and description, reflecting the current state and future direction of the project.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R3): Changed the framework name from "Auto-Agents-Framework" to "Autonomys Agents" and updated the description to emphasize the experimental nature of the framework, its current capabilities, and the call for feedback and contributions.
=> Update project description in README.md 

agent-memory-viewer/frontend/src/components/memory-views/ApprovedMemory.tsx, agent-memory-viewer/frontend/src/components/memory-views/RejectedMemory.tsx, agent-memory-viewer/frontend/src/types/index.ts
I spotted a minor bug while refactoring that we are not showing the thread.
This PR will fix that.
=> Fix thread issue on memory viewer

src/agents/tools/twitterTools.ts, src/agents/workflows/orchestrator/tools.ts
This pull request introduces several new tools for interacting with Twitter and refactors the existing Twitter tools into a single module. The changes primarily focus on creating new tools for fetching various types of tweets and posting tweets, as well as simplifying the tool creation process.
New Twitter tools and refactoring:
* [`src/agents/tools/twitterTools.ts`](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75R1-R206): Added new tools for fetching timeline tweets, recent replies, mentions, recent tweets, and posting tweets. The tools use `DynamicStructuredTool` and include appropriate logging and error handling.
Simplification of tool creation:
* [`src/agents/workflows/orchestrator/tools.ts`](diffhunk://#diff-55b82f5fb1f170f81a7e10c667ea1ad850222cc4534 …
=> Create version of twitter tools more optimized for orchestration workflow

README.md
Update README.md to include VS C++ redistributable dependency for windows users
=> Update README.md to include VS C++ redistributable dependency for windows users

characters/character.example/config/.env.example, src/config/index.ts
Previously we have an env var for agent version. Now, we are reading it from package.json
=> Read agent version from package.json

characters/character.example/config/config.example.yaml, src/agents/workflows/orchestrator/nodes.ts, src/agents/workflows/orchestrator/nodes/summaryNode.ts, src/agents/workflows/orchestrator/orchestratorWorkflow.ts, src/agents/workflows/orchestrator/prompts.ts, src/agents/workflows/orchestrator/types.ts, src/config/index.ts, src/config/schema.ts
This pull request introduces a new summary node to the orchestrator workflow, along with configuration updates and enhancements to the prompt system. The most important changes include the addition of the summary node and related configurations, as well as updates to the orchestrator workflow and prompt templates.
How it works? 
The orchestrator's summarization mechanism activates when the message queue exceeds `MAX_QUEUE_SIZE`, at which point it takes a slice of messages (excluding the first message, typically a system prompt) up to `MAX_WINDOW_SUMMARY` for summarization by the LLM. For example, in a conversation with six messages (a system prompt followed by five user/AI messages) and `MAX_WINDOW_SUMMARY` set to 3, the second through fourth messages would be summarized into a single …
=> Summarization Feature in Orchestrator Workflow

src/agents/tools/twitterTools.ts, src/agents/workflows/orchestrator/nodes/inputNode.ts, src/agents/workflows/orchestrator/prompts.ts
This pull request includes several changes to improve error handling and logging in the `twitterTools` and `orchestrator` modules. The most important changes include adding try-catch blocks to handle errors in asynchronous functions and improving the logging of results and usage metrics.
Error handling improvements:
* [`src/agents/tools/twitterTools.ts`](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75R174-R185): Added try-catch blocks in the `createLikeTweetTool` and `createFollowUserTool` functions to handle errors and log them appropriately. The functions now return an object indicating whether the operation was successful and any error message if applicable. [[1]](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75R174-R185 …
=> Twitter tool cleanups

characters/character.example/config/config.example.yaml, package.json, src/agents/tools/utils/dsn/api.ts, src/agents/tools/utils/dsn/autoDriveApi.ts, src/agents/tools/utils/dsn/dsnDownload.ts, src/agents/tools/utils/dsn/dsnUpload.ts, src/config/index.ts, src/config/schema.ts, yarn.lock
This pull request includes several changes to the configuration and dependencies, as well as refactoring to improve the codebase to resolve #201. The most important changes are grouped by theme below:
* Added a `network` parameter to the `auto_drive` configuration in `config.example.yaml`.
* Updated the `config` object to include `AUTO_DRIVE_NETWORK`.
* Updated the version of `@autonomys/auto-drive` and added `@autonomys/auto-utils` to `package.json`.
* Added `inquirer` back to `package.json` dependencies.
* Created a new `dsnApi` instance in `api.ts` and used it in `dsnDownload.ts` and `dsnUpload.ts` to avoid redundant code. [[1]](diffhunk://#diff-45669a41492073d2b7560a47cd25c8424dd1820a7709c936f0ef3accdc60cf62R1-R7) [[2]](diffhunk://#diff-60db8396b66a1d8c275e2b1e541d5d11f10c6bfb018ad85a4 …
=> Upgrade Auto-drive package and add Network to config file

.gitignore, src/agent.ts, src/agents/workflows/orchestrator/nodes.ts, src/agents/workflows/orchestrator/nodes/inputNode.ts, src/agents/workflows/orchestrator/nodes/messageSummaryNode.ts, src/agents/workflows/orchestrator/nodes/workflowSummaryNode.ts, src/agents/workflows/orchestrator/orchestratorWorkflow.ts, src/agents/workflows/twitter/twitterAgentTool.ts, src/config/index.ts, src/services/vectorDb/index.ts
This pull request is the **FIRST** PR toward maintaining mid-term memory and introduces changes to the orchestrator configuration and node creation processes in the codebase. The updates include the addition of a `namespace` parameter, integration of a `VectorDB` for vector storage, and modifications to various nodes to accommodate the new vector store.
**Orchestrator Configuration:**
* Added a `namespace` parameter to the orchestrator configuration and runner functions to help manage different workflows. (`src/agent.ts`, `src/agents/workflows/orchestrator/orchestratorWorkflow.ts`) [[1]](diffhunk://#diff-49cc4f0909411e6de89a20d5a97f81c481546b48973288ba70aeb002b0dd4138L15-R22) [[2]](diffhunk://#diff-49cc4f0909411e6de89a20d5a97f81c481546b48973288ba70aeb002b0dd4138R33) …
=> Integrating Vector DB with orchestration workflow and nodes

src/agents/workflows/orchestrator/nodes/inputNode.ts, src/agents/workflows/orchestrator/nodes/inputPrompt.ts, src/agents/workflows/orchestrator/orchestratorWorkflow.ts, src/agents/workflows/orchestrator/types.ts
Closes #209 
In order to make the workflow more robust and simpler to reason about, the `WorkflowControl` was added to state. Parsing of the return value from the LLM and state updating now happen inside the `inputNode`. Should the control fail to parse, `shouldStop:true` is returned. 
* [`src/agents/workflows/orchestrator/nodes/inputNode.ts`](diffhunk://#diff-0b266f27dd6b3b72ff592a029a20a2e6b185b4a148a142c29da1c950e6f1b3aaR3-L15): Added a `parseWorkflowControl` function to parse workflow control messages and handle errors. [[1]](diffhunk://#diff-0b266f27dd6b3b72ff592a029a20a2e6b185b4a148a142c29da1c950e6f1b3aaR3-L15) [[2]](diffhunk://#diff-0b266f27dd6b3b72ff592a029a20a2e6b185b4a148a142c29da1c950e6f1b3aaL27-R47)
* [`src/agents/workflows/orchestrator/nodes/inputPrompt.ts`](diffhunk://#diff-b …
=> Move workflow control to state to simplify parsing

src/agents/workflows/orchestrator/nodes/finishWorkflowPrompt.ts, src/agents/workflows/orchestrator/orchestratorWorkflow.ts, src/services/vectorDb/VectorDB.ts
This pull request includes several changes to enhance the workflow orchestration and vector database management. The most important changes include adding a method to check if the vector database is open, ensuring the vector store connection is opened before starting a new workflow, and updating the workflow summary prompt for better readability.
* [`src/services/vectorDb/VectorDB.ts`](diffhunk://#diff-6f0eb1e55d5be453d06aa8a839660cadce8baa5e193e4f6f262cb14a9d989b29R215-R226): Added `isOpen` method to check if the vector database connection is open and `open` method to initialize the database if it is not already open.
* [`src/agents/workflows/orchestrator/orchestratorWorkflow.ts`](diffhunk://#diff-b4dfd7878eec16efd1a0380da0464e07cc47af54ed1dc55b5fc0aefef7644059R82-R86): Added a check to …
=> Fix closed vector db bug

src/agents/tools/twitterTools.ts, src/agents/workflows/directedTwitter/nodes/collectDataNode.ts, src/agents/workflows/directedTwitter/nodes/generateTweetNode.ts, src/agents/workflows/directedTwitter/nodes/uploadToDsnNode.ts, src/agents/workflows/directedTwitter/tools.ts, src/agents/workflows/directedTwitter/tools/twitter/fetchMentionsTool.ts, src/agents/workflows/directedTwitter/tools/twitter/fetchMyRecentRepliesTool.ts, src/agents/workflows/directedTwitter/tools/twitter/fetchMyRecentTweetsTool.ts, src/agents/workflows/directedTwitter/tools/twitter/fetchTimelineTool.ts, src/agents/workflows/directedTwitter/tools/twitter/postTweetTool.ts, src/agents/workflows/directedTwitter/tools/twitter/utils/twitter.ts, src/agents/workflows/directedTwitter/tools/uploadToDsnTool.ts
Move directed twitter tools to directedTwitter folder in order, as it is the only place that use that version of the tools.
=> Move directed twitter tools to directedTwitter folder

examples/vectorDbExample.ts, package.json, src/services/vectorDb/VectorDB.ts
This pull request introduces several enhancements to the `VectorDB` service and adds a new example demonstrating its usage. The key changes include adding timestamp functionality to the content store, implementing a metadata-based search, and updating the `package.json` to include the new example.
Enhancements to `VectorDB` service:
* [`src/services/vectorDb/VectorDB.ts`](diffhunk://#diff-6f0eb1e55d5be453d06aa8a839660cadce8baa5e193e4f6f262cb14a9d989b29L94-R95): Added a `created_at` column to the `content_store` table to store timestamps. Updated the `INSERT` statement to include the `created_at` value. [[1]](diffhunk://#diff-6f0eb1e55d5be453d06aa8a839660cadce8baa5e193e4f6f262cb14a9d989b29L94-R95) [[2]](diffhunk://#diff-6f0eb1e55d5be453d06aa8a839660cadce8baa5e193e4f6f262cb14a9d989b29L149-R1 …
=> Enhance VectorDB: Add Timestamps, Metadata Search & New Example

src/index.ts
PR #228 introduced a new structure for result of workflow, `finishedWorkflowSchema`. This pull request includes a small change to the `src/index.ts` file to make it compatible. The change updates the variable `result.workflowSummary` to `result.summary` in the main function.
=> fix a typo in index file

examples/autonomousTwitterAgent/index.ts, examples/directedTwitterAgent/index.ts, src/agent.ts, src/index.ts
=> Fix few typos

README.md, cli/cli.ts, cli/components/ui.ts, cli/handlers/keyBindings.ts, cli/handlers/workflow.ts, cli/interactive.ts, cli/resurrect.ts, cli/types/types.ts, cli/utils/resurrection.ts, package.json, src/utils/logger.ts, yarn.lock
This pull request introduces an interactive CLI interface for managing and monitoring AI agents within the `Autonomys Agents` framework. The changes include updates to the documentation, new CLI components, and various utility functions to support the new interface.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R29-R52): Added instructions for using the interactive CLI interface, including features and keyboard shortcuts.
* [`cli/cli.ts`](diffhunk://#diff-27a1e29352de44fda3b963f97b4171445ebf8d6ad4b2d688ce6a0f2934a98863R1-R104): Implemented the main CLI logic, including the initialization of the UI, handling user input, and managing workflows and scheduled tasks.
* [`cli/components/ui.ts`](diffhunk://#diff-28b0e27e120f2c81d8b02345fadd11028d …
=> Interactive CLI for Managing & Monitoring Agents Flow and Scheduled Tasks

examples/twitterAgent/index.ts, src/agent.ts, src/agents/tools/twitterTools.ts, src/config/index.ts, src/config/twitter.ts, src/services/twitter/client.ts, src/services/twitter/types.ts
This pull request includes several changes to the Twitter agent configuration and tools, as well as updates to the Twitter API client. The twitter config wasn't capturing POST_TWEETS so posting was not working. Some tools were not being properly exported. Also, followUser was using the wrong field (userId). 
* `examples/twitterAgent/index.ts` and `src/agent.ts`: Changed the `temperature` parameter from `0` to `0.8` in the `orchestratorConfig` function. [[1]](diffhunk://#diff-b53615d38e5708e50f68e83b8a6dd0f9a1c3abddf56555240661d0ae643cb5a4L36-R36) [[2]](diffhunk://#diff-49cc4f0909411e6de89a20d5a97f81c481546b48973288ba70aeb002b0dd4138L28-R28)
* [`src/agents/tools/twitterTools.ts`](diffhunk://#diff-230c660f4e65058334d197eecd5d08fa4631f93b723a7648314029959f810c75L268-R271): Updated the …
=> Twitter Client and Tool Cleanup

src/agents/workflows/orchestrator/orchestratorWorkflow.ts
This pull request includes changes to the `createOrchestratorRunner` function in the `orchestratorWorkflow.ts` file to handle the opening and closing of the `vectorStore`. The most important changes ensure that the `vectorStore` is properly managed during the workflow execution.
Improvements to `vectorStore` management:
* [`src/agents/workflows/orchestrator/orchestratorWorkflow.ts`](diffhunk://#diff-b4dfd7878eec16efd1a0380da0464e07cc47af54ed1dc55b5fc0aefef7644059R110-R113): Added a check to open the `vectorStore` if it is not already open before starting the workflow.
* [`src/agents/workflows/orchestrator/orchestratorWorkflow.ts`](diffhunk://#diff-b4dfd7878eec16efd1a0380da0464e07cc47af54ed1dc55b5fc0aefef7644059L140-R152): Ensured the `vectorStore` is closed after the workflow data is …
=> Add closing and opening of vec db in workflow

src/agent.ts, src/agents/tools/vectorDbTools.ts, src/agents/workflows/orchestrator/orchestratorWorkflow.ts, src/agents/workflows/twitter/prompts.ts, src/agents/workflows/twitter/tools.ts, src/agents/workflows/twitter/twitterAgentTool.ts, src/services/vectorDb/VectorDB.ts
The changes primarily focus on integrating a new VectorDB tool, enhancing the orchestrator configuration, and updating the Twitter agent workflow.
* Added imports and initialization for `VectorDB` and `createVectorDbSearchTool` in `src/agent.ts` and `src/agents/workflows/twitter/tools.ts` to support vector database operations. [[1]](diffhunk://#diff-49cc4f0909411e6de89a20d5a97f81c481546b48973288ba70aeb002b0dd4138R13-R24) [[2]](diffhunk://#diff-63ae8a13aceacff3f9f7eed64cfb1c5afa186b3f7bfdd93dd42e49e14759e601L5-R18)
* Updated the `createVectorDbSearchTool` function to include metadata filtering and enhanced schema descriptions in `src/agents/tools/vectorDbTools.ts`.
* Modified `orchestratorConfig` to include the new `VectorDB` and search tool, and updated the tools array to incorporate …
=> Feature: Enable vector search tool

src/utils/logger.ts
This pull request includes several changes to the `src/utils/logger.ts` file to enhance the logger's flexibility and improve code readability. The most important changes include the addition of a new function to get the character path, refactoring the logger creation function to accept an options object, and using `path.join` for constructing file paths.
Enhancements to logger flexibility and readability:
* Added `getCharacterPath` function to dynamically determine the character path based on command-line arguments.
* Refactored the `createLogger` function to accept an options object (`LoggerOptions`) for more flexible logger configuration.
* Used `path.join` instead of string concatenation for constructing file paths in the `createTransports` function.
* Simplified the `stripAnsi` …
=> Refactor logger script - Remove dependency on global cfg

examples/twitterAgent/index.ts, src/agent.ts, src/agents/workflows/orchestrator/nodes.ts, src/agents/workflows/orchestrator/orchestratorWorkflow.ts, src/agents/workflows/orchestrator/types.ts, src/agents/workflows/twitter/twitterAgent.ts
The main update involves replacing the single `modelConfig` with a more comprehensive `modelConfigurations` object that supports multiple model configurations.
Key changes include:
* Updated `orchestratorConfig` in `examples/twitterAgent/index.ts` to use `modelConfigurations` instead of `modelConfig`, adding separate configurations for input, message summary, and finish workflow models.
* Updated `orchestratorConfig` in `src/agent.ts` to use `modelConfigurations` with separate configurations for different model types.
* Modified `OrchestratorConfig` and `OrchestratorRunnerOptions` types in `src/agents/workflows/orchestrator/types.ts` to replace `modelConfig` with `modelConfigurations`. [[1]](diffhunk://#diff-e1ae794f3d517bc8bfa38589ea4a340b93eef612ebc9dd6f8ce89c97cf881328R14-R21) …
=> Add ability to define model per orchestrator workflow node

src/agents/tools/twitter/index.ts, src/agents/tools/twitter/utils/utils.ts, src/agents/workflows/twitter/prompts.ts, src/agents/workflows/twitter/twitterAgent.ts, src/services/twitter/client.ts, src/services/twitter/types.ts
This is a quick "fix" to handle endless threads more effectively. Two things are done:
- add a `maxThreadDepth` with a default value of 5.
- Second, we added an `ignoreConversationIds` string array to the `getMyUnrepliedMentions` query. This is not actually populated anywhere yet. I have hardcoded a specific endless conversation into argu-mint's code. We will need to decide the best way to handle this in the future. Some ideas include: add to twitter config, let agent decide when a conversation is ready to be ignored and have it add to a persistent storage (sqlite, json, etc.) or have agent manager add to persistent storage.
Specific updates:
* [`src/agents/tools/twitter/utils/utils.ts`](diffhunk://#diff-9863d775dfeeabe3f3bc5078390bd20599e53a7c816b8cc5c84ea25c014dcda5R5): Added …
=> Manage endless threads more effectively

README.md, characters/character.example/config/character.example.yaml, examples/multiPersonality/README.md, examples/multiPersonality/index.ts, examples/twitterAgent/README.md, examples/twitterAgent/index.ts, package.json, src/agents/workflows/orchestrator/nodes.ts, src/agents/workflows/orchestrator/orchestratorWorkflow.ts, src/agents/workflows/orchestrator/types.ts, src/agents/workflows/twitter/prompts.ts, src/agents/workflows/twitter/twitterAgent.ts, src/agents/workflows/twitter/types.ts
This PR turned out doing more than I intended, it started as a simple README update. A couple of config issues were addressed as they were found during the process of improving documentation. Sorry for the kind of hodge podge PR but it seemed more efficient to leave it as one. I did add an example of a "multi-personality" agent @marc-aurele-besner! Hopefully, a more resonsible orchestrator can convince hindsight he isn't going to accidentally end all existence via Twitter posts!
Documentation Updates:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R40-R47): Added sections for "Known Issues" and updated the "Character System" to include more detailed descriptions and examples. [[1]](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac …
=> Improve and Add Example Code and Update README

examples/twitterAgent/index.ts, examples/web3Agent/README.md, examples/web3Agent/index.ts, package.json, src/agents/tools/autoDrive/index.ts, src/agents/tools/evm/index.ts, src/agents/tools/webSearch/index.ts
This pull request introduces a new example for creating an autonomous agent capable of interacting with blockchain networks, along with various other improvements and cleanups. The most important changes include adding the Web3 Agent example, updating the `package.json` to include the new example. Some minor updates were made to other tools and the twitter agent example.
* Added a new Web3 Agent example demonstrating how to create an autonomous agent for blockchain interactions. This includes the creation of tools for token transfers and balance checks, and the orchestration workflow setup. [[1]](diffhunk://#diff-f80fa0ccd6ad8171b53c553070b9c26f085915ef9591288b7eceabda1962d5a9R1-R87) [[2]](diffhunk://#diff-a33b6b0179fcd6f674567d3ecd18c04eebcf00e652804ed7ab5dc84e1bc606acR1-R42)
* Updated …
=> Feature: Add simple EVM tools (native transfer and balance check)

characters/character.example/config/character.example.yaml, src/agents/workflows/orchestrator/nodes/finishWorkflowPrompt.ts, src/agents/workflows/orchestrator/nodes/messageSummaryNode.ts, src/agents/workflows/orchestrator/orchestratorWorkflow.ts, src/config/characters.ts, src/config/schema.ts
Move message summary decision to conditional edge. Also, added frequency preferences to config and finish workflow prompt.
* [`src/agents/workflows/orchestrator/nodes/messageSummaryNode.ts`](diffhunk://#diff-8712f0e470d012359def290bb6cb8e4cad477279c8a885cb5b96ca7152bc3ffdL27): Removed unnecessary condition checks and simplified the return structure for the message summary node. [[1]](diffhunk://#diff-8712f0e470d012359def290bb6cb8e4cad477279c8a885cb5b96ca7152bc3ffdL27) [[2]](diffhunk://#diff-8712f0e470d012359def290bb6cb8e4cad477279c8a885cb5b96ca7152bc3ffdL55-L62)
* [`src/agents/workflows/orchestrator/orchestratorWorkflow.ts`](diffhunk://#diff-b4dfd7878eec16efd1a0380da0464e07cc47af54ed1dc55b5fc0aefef7644059L24-R27): Modified `handleConditionalEdge` to accept `pruningParameters` and added …
=> Refactor: Workflow improvements (message summary handling, finish workflow prompts, frequency preferences)

package.json
This pull request includes a version update for the `autonomys-agents` package. The version has been incremented from `0.2.2` to `0.3.0` to reflect the latest changes.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated the version from `0.2.2` to `0.3.0`.
=> upgrade to 0.3.0

src/agents/workflows/orchestrator/orchestratorWorkflow.ts, src/agents/workflows/twitter/twitterAgent.ts, src/config/index.ts
Empty `model_configuration` in character `config.yaml` wasn't being handled correctly. Additionally, updated default model to claude 3.7.
=> Update handling of empty model configurations and default to claude 3.7

src/services/twitter/client.ts
Fixed JSON circularity error when serializing Twitter threads by implementing a recursive solution that breaks circular references in tweet objects while preserving essential data.
- Error: `Converting circular structure to JSON`
- Impact: Unable to track engagement metrics on Twitter threads
- Root cause: Nested circular references through `inReplyToStatus` fields containing complete parent tweet objects
- Added `breakCircularReferences` utility function to recursively sanitize tweet objects
- Replaced full `inReplyToStatus` objects with simplified versions (just id, text, username)
- Applied the fix at all API touchpoints where tweets are returned
=> Fix Twitter Thread JSON Circularity Issue

src/agents/tools/slack/client.ts, src/agents/tools/slack/index.ts
This adds support for block kit in slack post message tool 
https://api.slack.com/block-kit
=> Add support for block-kit in Slack post message tool

src/agents/tools/slack/README.md, src/agents/tools/slack/index.ts
I had forgotten to add these 2 reactions functions in `createSlackTools` 🤦‍♂️
=> Add both reactions tools to createSlackTools

examples/githubAgent/index.ts, package.json, src/agents/tools/github/README.md, src/agents/tools/github/client.ts, src/agents/tools/github/index.ts, src/config/index.ts, src/config/schema.ts, yarn.lock
- List issues on specific repo
- Create issues
- List comments on an issue
- Create a comment on the issue
- React to a comment
- List mentions
- List notifications
- List pull requests
- Get pull request details
- List PR comments
- Create PR comment
- React to PR
- Watch&Un-watch repo
- List watched repo
https://github.com/autonomys/autonomys-agents/issues/301
=> Add GitHub tools

examples/vectorDbExample.ts, package.json, scripts/migrate-vector-db.ts, src/agents/tools/vectorDb/index.ts, src/agents/workflows/orchestrator/tools.ts, src/api/controller/prompt/ChatPrompts.ts, src/services/vectorDb/VectorDB.ts
This pull request includes several changes to the vector database functionality. The most important changes are:
- Creation of new tool for querying the vector database content directly with standard SQL query.
- Use SQL filters for searches (rather than metadata filter)
(Optional) A migration script was added due to the changing of `created_at` from TEXT to DATETIME. However, in testing the migration isn't needed, everything seems to work even when the field is TEXT. Migrating is still recommended.
Enhancements to search functionality:
* [`examples/vectorDbExample.ts`](diffhunk://#diff-b589fc6721e9bf81bc17cd26ee7eb67a7f0f715f8cc1f08a2e3855e3b1932943L37-R76): Replaced metadata filters with SQL filters for searches and added examples of direct SQL queries and content filtering. …
=> Add tool to query content directly within vector db

src/agents/tools/slack/chat.ts, src/agents/workflows/orchestrator/nodes/inputPrompt.ts, src/agents/workflows/orchestrator/orchestratorWorkflow.ts, src/agents/workflows/slack/prompts.ts, src/agents/workflows/slack/slackAgent.ts, src/agents/workflows/twitter/twitterAgent.ts, src/utils/logger.ts
All of the sudden workflows have been getting stuck in infinite (at least to recursion limits) saving experiences and just not being logical around when to stop a workflow. I updated prompts and downgraded to claude-3-5-sonnet, as it seemed to work better.
This pull request includes several updates to improve the functionality and maintainability of the codebase, particularly focusing on Slack message handling, workflow prompts, and model configurations. The most important changes are summarized below:
* Enhanced the `createPostSlackMsgTool` to check for similar messages before posting to avoid duplicates and to return a structured response indicating success or failure. (`src/agents/tools/slack/chat.ts`) [[1]](diffhunk://#diff-15ca4623b39755be76c6e30e95d354d7c232d270e9cff20dd7d12cb8632e90 …
=> Prompt Updates to Add Workflow Stability

src/agents/workflows/orchestrator/scheduler/db/dbController.ts, src/agents/workflows/orchestrator/scheduler/db/schedulerDb.ts, src/agents/workflows/orchestrator/scheduler/db/schema.ts, src/agents/workflows/orchestrator/scheduler/taskQueue.ts, src/agents/workflows/orchestrator/scheduler/types.ts, src/services/sqlite/SqliteDB.ts
This PR introduces SQLite database persistence for the existing task scheduler system. This enhancement improves reliability by ensuring scheduled tasks persist across server restarts and provides better task state management.
- Modified `src/agents/workflows/orchestrator/scheduler/taskQueue.ts` to integrate with SQLite database through dbController methods:
- Added database loading of tasks on initialization
- Implemented persistence for task creation and status updates
- Added error handling for database operations
- Added database controller functions for task operations:
- getTasks to retrieve tasks by namespace and status
- createTask to persist new scheduled tasks
- markTaskAsProcessing, markTaskAsCompleted, markTaskAsFailed for status transitions
- deleteTask for task removal
- …
=> Add SQLite Database Integration for Task Scheduler

src/agents/workflows/orchestrator/nodes/inputPrompt.ts, src/agents/workflows/twitter/prompts.ts
With this pull request I was able to get `claude-3-5-haiku-latest` to work consistently, using it as the model for all underlying workflows/agents. 
This pull request includes significant updates to the workflow and prompt logic to enhance clarity and functionality. The changes focus on refining the rules for stopping the workflow, improving the decision-making process, and updating instructions for Twitter prompts.
Probably fixes #338 
* [`src/agents/workflows/orchestrator/nodes/inputPrompt.ts`](diffhunk://#diff-b2e08db2b9f277c67d3851b990977574059546cf698db5688d8237a7a55d7669L22-R54): Consolidated and clarified the rules for stopping the workflow, including defining universal workflow control rules, tool capability assessment, and stop/continue conditions.
* …
=> Input Prompt Improvements

package.json, src/services/twitter/auth.ts, src/services/twitter/client.ts, src/services/twitter/utils.ts, yarn.lock
This pull request introduces a significant improvement to the Twitter authentication process by adding cookie-based authentication and retry logic with exponential backoff. The changes include updates to the authentication mechanism and refactoring of the Twitter client code to utilize the new authentication module.
Authentication enhancements:
* [`src/services/twitter/auth.ts`](diffhunk://#diff-6cc340f1f5df0a795165bdabb9a13ee06651f2ba5426c638943f9ce6d8db59d3R1-R119): Added a new module for Twitter authentication that includes cookie-based authentication, login with username and password, and retry logic with exponential backoff.
Refactoring Twitter client:
* [`src/services/twitter/client.ts`](diffhunk://#diff-9630eb2796eecdfade33ba5ad88277b7d43c3d8f2d1bd32765da2ba202133addL2-R8): …
=> Add retry with backoff to twitter login

src/agents/tools/scheduler/index.ts, src/agents/workflows/orchestrator/nodes/inputPrompt.ts, src/agents/workflows/slack/prompts.ts, src/agents/workflows/twitter/prompts.ts
This pull request includes several updates to improve the guidance and best practices for task scheduling and communication tools. The changes enhance clarity and provide more detailed instructions for various scenarios.
Updates to task scheduling tools:
* [`src/agents/tools/scheduler/index.ts`](diffhunk://#diff-2349c678b38d1c71395515e1e19312e3a5ae39e60f2dec54f416cedadf9557ecR46): Added a guideline to check the existing schedule before adding new tasks to avoid scheduling similar tasks at the same time.
* [`src/agents/tools/scheduler/index.ts`](diffhunk://#diff-2349c678b38d1c71395515e1e19312e3a5ae39e60f2dec54f416cedadf9557ecL108-R113): Updated the description for deleting tasks to include scenarios where tasks are scheduled at the wrong time.
Enhancements to workflow prompts:
* …
=> Prompt improvements

agent-package-manager/src/commands/publish.ts, agent-package-manager/src/config/default.ts, agent-package-manager/src/index.ts, agent-package-manager/src/utils/blockchain/AutonomysPackageRegistry.abi.json, agent-package-manager/src/utils/blockchain/contractClient.ts, agent-package-manager/src/utils/blockchain/errorHandler.ts, agent-package-manager/src/utils/blockchain/types.ts, agent-package-manager/src/utils/commands/registry/toolInquiry.ts, agent-package-manager/src/utils/commands/registry/updateRegistry.ts
- Updated contract ABI, make it compatible with new contract version. See PR #367 
- Enhanced error handling in registry updates with transaction hash tracking
- Improved publish command feedback with transaction hash display
- Removed redundant master password storage notification
- Added transaction hash return value to `updateRegistry` function
- Implemented proper error propagation in publish command
- Updated registry cache handling with transaction verification 
Since we are using hash of names (for gas efficiency), we need to introduce a registry webserver to improve UX for devs and users. I'll add this in future PRs.
=> Upgrade Package Manager for New Contract

src/blockchain/agentExperience/cidManager.ts, src/utils/retry.ts
Agent experiences need to work reliably even when blockchain RPC connections fail. While we already have local storage fallback, the error handling and messaging needed improvement.
- Improved error handling in blockchain operations
- Enhanced local storage fallback mechanism
- Ensure experience hashes are always saved locally, even when blockchain sync fails
- Verified with both working and failing RPC endpoints
- Confirmed local storage fallback works as expected
- Validated data integrity is maintained during RPC failures
=> Make Agent Experiences Resilient to RPC Failures

web-cli/src/components/input/InputArea.tsx, web-cli/src/components/input/styles/InputStyles.ts, web-cli/src/components/status/StatusBox.tsx, web-cli/src/components/status/styles/StatusStyles.ts, web-cli/src/components/tasks/ScheduledTasksBox.tsx, web-cli/src/components/tasks/TaskHeader.tsx, web-cli/src/components/tasks/TasksArea.tsx, web-cli/src/components/tasks/styles/ScheduledTasksBoxStyles.ts, web-cli/src/components/tasks/styles/TaskHeaderStyles.ts, web-cli/src/components/tasks/styles/TasksAreaStyles.ts, web-cli/src/services/Api.ts, web-cli/src/services/WorkflowService.ts, web-cli/src/types/types.ts
- **Style Refactoring**: Extracted UI styles from InputArea component to dedicated styles file for better maintainability
- **New Feature**: Added workflow stop functionality to the input component
- **Status Handling**: Implemented status display for workflow stopping operations
- Created `InputStyles.ts` to house all component styles using Chakra UI props typing
- Integrated `stopWorkflow` service functionality
- Added status state management for stop operations with appropriate timeout cleanup
These changes improve code maintainability through separation of concerns while adding the ability for users to stop running workflows.
=> Web CLI Components refactoring and Workflow Stop Feature

core/src/agents/tools/slack/canvas.ts, core/src/agents/tools/slack/chat.ts, core/src/agents/tools/slack/utils/chat.ts, core/src/agents/tools/slack/utils/types.ts, core/src/agents/workflows/orchestrator/nodes/toolExecutionNode.ts, core/src/agents/workflows/slack/prompts.ts
Enhance Slack tools with detailed schemas for canvas and chat block o3-mini fails without it. 🤷‍♂️
This pull request includes significant schema validation improvements for Slack tools within the `core/src/agents/tools/slack` directory. The changes introduce new schemas for validating canvas blocks, canvas changes, and message blocks, enhancing the structure and reliability of the data being processed.
UPDATE: Also added block data to messages returned in list messages tool. This may be one reason why argu-mint repeated himself so much, he didn't see what he was saying when using blocks.
* [`core/src/agents/tools/slack/canvas.ts`](diffhunk://#diff-9d296e1412e38adcfa68427ebcdf4f2b3d8418bec091b032b0c3499fedc1db66R14-R46): Introduced `canvasBlockSchema`, `canvasChangeSchema`, and …
=> Enhance Slack tools with detailed schemas for canvas and chat block

core/src/agent.ts
This pull request introduces changes to the `core/src/agent.ts` file to enhance model configuration management by adding new model configurations and updating the orchestrator configuration.
Enhancements to model configuration management:
* Added imports for `ModelConfigurations` and `LLMConfiguration` from `types.js` and `llm/types.js` respectively. Defined `bigModel`, `smallModel`, and `modelConfigurations` constants to manage different model configurations.
* Updated the `orchestratorConfig` function to include `modelConfigurations` in the returned `OrchestratorRunnerOptions` object. [[1]](diffhunk://#diff-db431acd2456bd1c6a341db7a6a574210a00f5fd6bc7f3550178d4c2fcc97e70R125) [[2]](diffhunk://#diff-db431acd2456bd1c6a341db7a6a574210a00f5fd6bc7f3550178d4c2fcc97e70L125-R147)
* Changed the …
=> Custom model configurations in agent.ts

web-cli/package.json, web-cli/src/App.css, web-cli/src/App.tsx, web-cli/src/components/BodyArea.tsx, web-cli/src/components/header/LogoBox.tsx, web-cli/src/components/input/styles/InputStyles.ts, web-cli/src/components/logs/OutputLog.tsx, web-cli/src/components/logs/styles/LogStyles.ts, web-cli/src/components/tasks/ScheduledTasksBox.tsx, web-cli/src/components/tasks/styles/ScheduledTasksBoxStyles.ts, web-cli/src/components/tasks/styles/TaskHeaderStyles.ts, web-cli/src/components/tasks/styles/TasksAreaStyles.ts
This PR implements a new two-panel layout structure for the Web CLI interface, providing a better user experience with side-by-side content instead of stacked components.
- Created a responsive two-panel layout with left and right sections
- Left panel: Contains input area and tasks area
- Right panel: Contains output logs
- Improved responsive behavior for different screen sizes
- Updated component heights and styling to better utilize screen space
- Fixed overflow and scrolling behavior across components
- Enhanced visual separation between panels with subtle borders and shadows
- Implemented via CSS Grid/Flexbox for optimal layout control
- Dynamically adjusts heights based on viewport size
- Automatic panel resizing on window resize events
- Maintains proper scrolling behavior within …
=> Two-Panel Layout Implementation For Web Cli

README.md, core/package.json, core/src/agents/tools/twitter/auth.ts, examples/multiPersonality/README.md, examples/package.json, examples/twitterAgent/README.md, examples/web3Agent/README.md, yarn.lock
This PR addresses a bug in the Twitter agent's authentication logic where the system would repeatedly attempt cookie-based authentication even when the cookie file was missing. The fix ensures that the retry logic immediately stops and proceeds to fresh login if the cookie file does not exist.
Previously, the authentication flow for the Twitter agent used a retry loop for cookie-based authentication. If the cookie file was missing, the code would return `undefined` and the retry loop would continue, resulting in multiple unnecessary attempts to authenticate with cookies. This caused delays and redundant log messages before the system would finally attempt a fresh login with username and password.
- The code now throws an error with the message `No cookie file exists` if the cookie file is …
=> Bug: Twitter auth

package.json
=> Bump repo version to v0.6.0

agent-package-manager/CHANGELOG.md, agent-package-manager/package.json, core/package.json
I forgot to bump their versions in package.json in the last PR.
=> update agent-core and agent-os package.json

README.md, docker/web-cli/.dockerignore, docker/web-cli/Dockerfile, docker/web-cli/docker-compose.yml, docker/web-cli/entrypoint.sh, web-cli/src/react-app-env.d.ts, web-cli/src/services/Api.ts
This PR adds Docker support for the Web CLI interface, making it easier to deploy and run the web interface in containerized environments. The implementation includes runtime configuration management and improved API configuration handling.
- Added Dockerfile for Web CLI with multi-stage build process
- Created docker-compose.yml for easy deployment
- Added .dockerignore for optimized builds
- Implemented entrypoint script for runtime configuration injection
- Enhanced API configuration to support both runtime and build-time variables
- Updated TypeScript definitions to include runtime configuration types
- Implemented fallback chain for API configuration:
1. Runtime configuration
2. Environment variables
3. Default values
- Made API base URL and token configuration more flexible
- Added …
=> Add Docker Support for Web CLI

core/src/agents/chat/config.ts, core/src/agents/chat/index.ts, core/src/agents/chat/nodes.ts, core/src/agents/chat/nodes/executor.ts, core/src/agents/chat/nodes/input.ts, core/src/agents/chat/nodes/prompt.ts, core/src/agents/chat/state.ts, core/src/agents/chat/tools.ts, core/src/agents/chat/types.ts, core/src/agents/chat/workflow.ts, core/src/api/controller/ChatController.ts, core/src/api/routes/chat.ts, core/src/api/routes/index.ts, core/src/api/server.ts, core/src/api/types.ts, examples/twitterAgent/index.ts
This PR introduces a new chat workflow system that provides a unified and extensible way to handle chat interactions within the Autonomys Agents ecosystem.
This is the **first part** of a planned PR series to improve chat capabilities across the platform. This PR focuses on the core infrastructure for the chat workflow.
- Created a new chat workflow implementation with a state-graph based architecture
- Implemented chat nodes (input, executor) for message processing and tool execution
- Added tool integration capabilities to the chat system
- Updated API endpoints to use the new chat workflow
- Integrated the chat workflow into the Twitter Agent example
- **State Management**: Added a `ChatState` class to handle message history and tool calls
- **Node Architecture**: 
- `InputNode`: …
=> Add Features and Refactor Chat Capability (Part 1)

core/src/api/controller/ChatController.ts, web-cli/.env.sample, web-cli/eslint.config.js, web-cli/package.json, web-cli/src/components/BodyArea.tsx, web-cli/src/components/NamespaceTabs.tsx, web-cli/src/components/chat/ChatArea.tsx, web-cli/src/components/chat/components/ChatHeader.tsx, web-cli/src/components/chat/components/ChatInput.tsx, web-cli/src/components/chat/components/ChatMessage.tsx, web-cli/src/components/chat/index.ts, web-cli/src/components/chat/styles/ChatStyles.ts, web-cli/src/components/input/InputArea.tsx, web-cli/src/components/status/styles/StatusStyles.ts, web-cli/src/components/tabs/TabNavigation.tsx, web-cli/src/components/tabs/styles/TabNavigationStyles.ts, web-cli/src/hooks/useBodyLeftSide.ts, web-cli/src/services/Api.ts, web-cli/src/services/ChatService.ts, web-cli/src/types/types.ts
This PR introduces several UI improvements to the web client, restructures the layout components, and modifies the chat response format. It also updates ESLint configuration to better support browser APIs and React development.
- **Chat Response Format Update**: 
- Modified `ChatController.ts` to return only the most recent message in the response instead of mapping all messages, simplifying the response object.
- **Code Organization**:
- Moved task management logic from `BodyArea.tsx` to a custom hook (`useBodyLeftSide.ts`), following better React practices and improving code maintainability.
- Introduced `TabNavigation` component for switching between Agent and Chat views.
- **UI Improvements**:
- Enhanced chat layout with better resizing capabilities
- Optimized height configurations …
=> UI Improvements and Chat Agent Integration (Part 4)

core/CHANGELOG.md, core/package.json, core/src/agents/chat/index.ts, core/src/agents/index.ts, package.json, web-cli/package.json, web-cli/src/components/header/LogoBox.tsx
Following the changes in serial PRs (#416 #417 #418 #419)
=> Bump agent-core, web-cli, repo versions
